// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaRaKYMuPe_yHraOMVlMtnhXPJCGsJzO4',
    appId: '1:763177495346:web:65ec141193b4a8b8f8452b',
    messagingSenderId: '763177495346',
    projectId: 'login-d1911',
    authDomain: 'login-d1911.firebaseapp.com',
    storageBucket: 'login-d1911.appspot.com',
    measurementId: 'G-RBLEMB6QE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7voJJ-z_Uy7wp9g2CLtsg51F-bi2YJ_U',
    appId: '1:763177495346:android:5206cca6ebbfab89f8452b',
    messagingSenderId: '763177495346',
    projectId: 'login-d1911',
    storageBucket: 'login-d1911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVUgGU1HOa3xz6txj_ZKckJphMIeI5GQ',
    appId: '1:763177495346:ios:6c0c6f3b8129bb70f8452b',
    messagingSenderId: '763177495346',
    projectId: 'login-d1911',
    storageBucket: 'login-d1911.appspot.com',
    androidClientId: '763177495346-1imag4a8oq06gurl8d78ophnfse9lc6n.apps.googleusercontent.com',
    iosClientId: '763177495346-hjlmk4pjtvp086lgapfqu5gr3f2nkjgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyVUgGU1HOa3xz6txj_ZKckJphMIeI5GQ',
    appId: '1:763177495346:ios:d2360bb5e52a8ce4f8452b',
    messagingSenderId: '763177495346',
    projectId: 'login-d1911',
    storageBucket: 'login-d1911.appspot.com',
    androidClientId: '763177495346-1imag4a8oq06gurl8d78ophnfse9lc6n.apps.googleusercontent.com',
    iosClientId: '763177495346-pu7781lk35jghhnjbajh6qkvm3f54u15.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAplication.RunnerTests',
  );
}
